import {Activity,ArrowDownUp,ArrowUpRight,Clock3,Globe2,History,Power,ShieldCheck,Signal,Wifi,Zap} from 'lucide-react'
import type {Snapshot,Network} from '../types'
import {Timeline} from '../components/Charts'
import {displayDate} from '../services/api'
function duration(s:number){return s>=3600?Math.floor(s/3600)+'h '+Math.floor(s%3600/60)+'m':Math.floor(s/60)+'m '+s%60+'s'}
export function Dashboard({data,busy,run,navigate,networkList}:{data:Snapshot;busy:boolean;run:(path:string)=>void;navigate:(page:string)=>void;networkList:(n:Network[])=>React.ReactNode}){
 const c=data.current,n=c.network
 return <><div className="dashboard-grid"><section className="panel connection-panel"><div className="panel-heading"><span className="section-label"><Wifi size={17}/>CURRENT CONNECTION</span><span className={'badge '+(n?'mint':'neutral')}>{n?'Connected':'Disconnected'}</span></div><div className="connection-body"><div><h2 className="ssid-title">{n?.ssid||'A better connection starts here'}</h2><p>{n?<>{n.security} <span className="separator">/</span> {n.band||'Band unavailable'} <span className="separator">/</span> {n.trusted?'Trusted network':'Outside trusted list'}</>:'Save a network you trust, then let WiFiSense do the rest.'}</p><div className="connection-details"><span><ShieldCheck size={14}/>{n?.trusted?'Authorized network':'Awaiting authorization'}</span><span><Clock3 size={14}/>{duration(c.connection_duration_seconds)}</span></div></div><div className="signal-orb" style={{'--signal':(n?.signal_strength||0)*3.6+'deg'} as React.CSSProperties}><div><Wifi size={23}/><strong>{n?.signal_strength??'—'}<small>{n?'%':''}</small></strong><span>{n?.quality||'NO SIGNAL'}</span></div></div></div><div className="connection-footer"><span><i className="status-dot"/>{data.system.monitoring?'Monitoring every '+data.settings.monitoring_interval+' seconds':'Monitor paused'}</span>{n?<button className="text-button" disabled={busy} onClick={()=>run('/wifi/disconnect')}><Power size={14}/>Disconnect</button>:<button className="text-button mint" onClick={()=>navigate('Nearby Networks')}>Find a network <ArrowUpRight size={15}/></button>}</div></section><section className="panel automation-panel"><div className="panel-heading"><div className="purple-icon"><Zap size={20}/></div><label className="switch" aria-label="Enable auto connect"><input type="checkbox" checked={c.auto_connect} disabled={busy} onChange={e=>run('/wifi/auto-connect/'+(e.target.checked?'enable':'disable'))}/><span/></label></div><h2>Always on the best network.</h2><p>Intelligent selection keeps you connected to the strongest trusted connection.</p><div className="automation-foot"><span className="badge purple">Auto-connect {c.auto_connect?'enabled':'paused'}</span><button aria-label="Configure automation" className="icon-button" onClick={()=>navigate('Settings')}><ArrowUpRight size={18}/></button></div></section></div>
 <div className="stats-grid"><Stat icon={Globe2} label="Internet access" value={c.connectivity?(c.connectivity.internet_available?'Online':'Unavailable'):'Not checked'} hint={c.connectivity?'DNS '+(c.connectivity.dns_working?'resolving':'unavailable'):'Verified after trusted connection'}/><Stat icon={Activity} label="Network latency" value={c.connectivity?.latency_ms!=null?c.connectivity.latency_ms+' ms':'—'} hint={c.connectivity?.probe||'Waiting for a measurement'}/><Stat icon={Signal} label="Connection score" value={n?.score!=null?n.score.toFixed(1):'—'} hint="Signal · internet · latency · stability"/><Stat icon={ShieldCheck} label="Trusted networks" value={String(data.trusted.length).padStart(2,'0')} hint={data.networks.filter(x=>x.trusted).length+' currently in range'}/></div>
 <div className="lower-grid"><section className="panel"><div className="panel-heading"><div><h2>Signal performance</h2><p className="muted">Recent connection measurements</p></div><span className="chart-key"><i/>Signal strength</span></div><Timeline data={data.metrics.connections}/></section><section className="panel"><div className="panel-heading"><h2>Recent activity</h2><button className="text-button" onClick={()=>navigate('Connection History')}>View all <ArrowUpRight size={14}/></button></div><div className="activity-list">{data.events.length?data.events.slice(0,4).map(e=><div className="activity-item" key={e.id}><div className="activity-icon">{e.event==='switched'?<ArrowDownUp size={16}/>:<Activity size={16}/>}</div><div><strong>{e.event.replaceAll('_',' ')}</strong><p>{e.ssid||'WiFiSense settings'}</p><small>{displayDate(e.timestamp)}</small></div></div>):<div className="empty compact"><History/><p>Your connection activity will appear here.</p></div>}</div></section></div><section className="panel networks-panel"><div className="panel-heading"><div><h2>Nearby trusted networks <span className="count">{data.networks.filter(x=>x.trusted).length}</span></h2><p className="muted">Authorized connections, ranked by overall quality.</p></div><button className="text-button" onClick={()=>navigate('Nearby Networks')}>Explore networks <ArrowUpRight size={15}/></button></div>{networkList(data.networks.filter(x=>x.trusted))}</section></>
}
function Stat({icon:Icon,label,value,hint}:{icon:typeof Wifi;label:string;value:string;hint:string}){return <section className="panel stat"><div className="stat-label">{label}<Icon size={17}/></div><strong>{value}</strong><small>{hint}</small></section>}
