import {useState} from 'react'
import {Activity,BarChart3,Check,ChevronRight,History,LayoutDashboard,Menu,Plus,Radio,RefreshCw,Settings2,ShieldCheck,Wifi,X} from 'lucide-react'
import {useNetwork} from './hooks/useNetwork'
import {api,displayDate} from './services/api'
import type {Network,Settings} from './types'
import {NetworkList} from './components/NetworkList'
import {TrustDialog} from './components/TrustDialog'
import {SettingsPage} from './pages/SettingsPage'
import {Dashboard} from './pages/Dashboard'
import {Analytics} from './pages/Analytics'
const nav=[{name:'Dashboard',icon:LayoutDashboard},{name:'Nearby Networks',icon:Radio},{name:'Trusted Networks',icon:ShieldCheck},{name:'Connection History',icon:History},{name:'Analytics',icon:BarChart3},{name:'Settings',icon:Settings2}]
const subtitles:Record<string,string>={'Dashboard':'Your connections, working in harmony.','Nearby Networks':'Discover your surroundings. Connect with confidence.','Trusted Networks':'Your networks. Your permission. Your control.','Connection History':'Every connection has a story.','Analytics':'A clearer picture of your network performance.','Settings':'Make your connection work your way.'}
export default function App(){
 const {data,error,loading,refresh}=useNetwork()
 const [page,setPage]=useState('Dashboard'),[trust,setTrust]=useState<Network|null|undefined>(undefined),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[actionError,setActionError]=useState(''),[filter,setFilter]=useState(''),[menu,setMenu]=useState(false)
 async function action(path:string,method='POST',body?:unknown,success='Changes saved'){
  setBusy(true);setActionError('');setMessage('')
  try{await api(path,method,body);await refresh();setMessage(success)}catch(e){setActionError(e instanceof Error?e.message:'Operation failed');throw e}finally{setBusy(false)}
 }
 const run=(path:string,method='POST',body?:unknown,success?:string)=>{void action(path,method,body,success).catch(()=>{})}
 const navigate=(name:string)=>{setPage(name);setMenu(false);setFilter('')}
 const networkList=(networks:Network[])=><NetworkList networks={networks} onTrust={setTrust} onConnect={id=>run('/wifi/connect/'+id,'POST',undefined,'Network connected')} busy={busy}/>
 return <div className="app-shell"><aside className={'sidebar '+(menu?'open':'')}><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('Dashboard')}}><div className="brand-mark"><Wifi size={24}/></div><span>WiFi<span className="mint">Sense</span><small>NETWORK INTELLIGENCE</small></span></a><div className="nav-label">WORKSPACE</div><nav>{nav.map(item=><button aria-label={item.name} key={item.name} className={'nav-item '+(page===item.name?'selected':'')} onClick={()=>navigate(item.name)}><item.icon size={18}/>{item.name}{item.name==='Nearby Networks'&&<span className="nav-count">{data?.networks.length||0}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="privacy-card"><ShieldCheck size={20}/><strong>Trusted by design</strong><p>Only your authorized networks. Credentials stay on your device.</p></div><div className="local-status"><i className="status-dot"/><span>Local workspace<small>{data?.system.mode==='system'?'System adapter':'Simulation environment'}</small></span><span className="version">v1.0</span></div></div></aside><div className="main-shell"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="breadcrumb">Workspace <ChevronRight size={13}/> <strong>{page}</strong></div><div className="topbar-right"><span className="badge mode"><span className="status-dot"/>{data?.system.mode==='system'?'System mode':'Simulation mode'}</span><span className="avatar">WS</span></div></header><main><div className="page-heading"><div><div className="eyebrow">INTELLIGENT CONNECTIONS</div><h1>{page}</h1><p>{subtitles[page]}</p></div><button className="button" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={15}/>Refresh</button></div>{(error||actionError||data?.system.error)&&<div className="error" role="alert">{error||actionError||data?.system.error}</div>}{message&&<div className="notice" role="status"><Check size={16}/>{message}<button className="icon-button" aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={15}/></button></div>}{loading&&!data?<div className="panel empty"><Activity/><h2>Finding your connection…</h2></div>:!data?<div className="panel empty"><Wifi/><h2>Backend unavailable</h2><p>Start the WiFiSense backend on 127.0.0.1:8000, then refresh.</p></div>:<>
 {page==='Dashboard'&&<Dashboard data={data} busy={busy} run={run} navigate={navigate} networkList={networkList}/>}
 {page==='Nearby Networks'&&<section className="panel"><div className="panel-heading"><div><h2>Available networks <span className="count">{data.networks.length}</span></h2><p className="muted">Untrusted networks are visible but never eligible for automatic connection.</p></div><input className="search" aria-label="Search networks" placeholder="Search networks…" value={filter} onChange={e=>setFilter(e.target.value)}/></div>{networkList(data.networks.filter(x=>x.ssid.toLowerCase().includes(filter.toLowerCase())))}</section>}
 {page==='Trusted Networks'&&<><div className="section-toolbar"><span className="muted">Credentials are never shown or returned by the API.</span><button className="button primary" onClick={()=>setTrust(null)}><Plus size={16}/>Add trusted network</button></div><div className="trusted-grid">{data.trusted.length?data.trusted.map(t=><section className="panel trusted-card" key={t.id}><div className="panel-heading"><div className="big-icon"><ShieldCheck/></div><span className="badge mint">Authorized</span></div><h2>{t.ssid}</h2><p className="muted">{t.security} · {t.bssid||'Any matching access point'}</p><label className="setting-toggle"><span>Allow auto-connect</span><input type="checkbox" checked={t.auto_connect_enabled} disabled={busy} onChange={e=>run('/wifi/trusted/'+t.id,'PATCH',{auto_connect_enabled:e.target.checked})}/></label><label>Priority (-10 to 10)<input aria-label={'Priority for '+t.ssid} type="number" min="-10" max="10" defaultValue={t.priority} onBlur={e=>{const value=Number(e.target.value);if(Number.isInteger(value)&&value>=-10&&value<=10&&value!==t.priority)run('/wifi/trusted/'+t.id,'PATCH',{priority:value})}}/></label><small>Last connected: {t.last_connected_at?displayDate(t.last_connected_at):'Never'}</small><div className="card-actions"><button className="button" disabled={busy} onClick={()=>run('/wifi/connect/'+t.id,'POST',undefined,'Network connected')}>Connect</button><button className="text-button danger" disabled={busy} onClick={()=>{if(window.confirm('Remove '+t.ssid+' from trusted networks and delete its WiFiSense credential?'))run('/wifi/trusted/'+t.id,'DELETE',undefined,'Network removed')}}>Forget network</button></div></section>):<section className="panel empty"><ShieldCheck/><h2>Your trusted circle starts here</h2><p>Add an authorized network to enable secure connection management.</p><button className="button primary" onClick={()=>setTrust(null)}>Add trusted network</button></section>}</div></>}
 {page==='Connection History'&&<section className="panel"><div className="panel-heading"><h2>Connection & audit log</h2><input className="search" aria-label="Filter history" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter events or networks…"/></div><div className="table-wrap"><table><thead><tr><th>Event</th><th>Network</th><th>Details</th><th>Time</th></tr></thead><tbody>{data.events.filter(e=>(e.event+' '+e.ssid).toLowerCase().includes(filter.toLowerCase())).map(e=><tr key={e.id}><td><span className="event-pill">{e.event.replaceAll('_',' ')}</span></td><td>{e.ssid||'—'}</td><td>{e.detail||'—'}</td><td>{displayDate(e.timestamp)}</td></tr>)}</tbody></table>{!data.events.length&&<div className="empty"><History/><p>No recorded events yet.</p></div>}</div><p className="muted footnote">Showing the latest 500 events. Records are retained for 30 days.</p></section>}
 {page==='Analytics'&&<Analytics data={data}/>}
 {page==='Settings'&&<SettingsPage key={JSON.stringify(data.settings)} initial={data.settings} trusted={data.trusted} busy={busy} onSave={async(s:Settings)=>{await action('/settings','PUT',s,'Settings saved')}}/>}
 </>}<footer><span><ShieldCheck size={13}/> Private by design. Managed locally.</span><span>WiFiSense · Intelligent Wi-Fi management</span></footer></main></div>{trust!==undefined&&<TrustDialog network={trust} onClose={()=>setTrust(undefined)} onSave={async body=>{await action('/wifi/trusted','POST',body,'Network added to your trusted list')}}/>}</div>
}
